config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  
  resources :greetings, only: [:index]
  resources :news, only: [:index, :show]
  resources :histories, only: [:index]
  resources :visions, only: [:index]
  resources :members, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  def index
    #@greetings = Greeting.all
  end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  def index
    # @Histories = History.all
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    #@members = Members.all
  end
  def show
    #@member = Member.find(params[:id])
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    #@news = New.all
  end

  def show
    #@new = New.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/visions_controller.rb
class VisionsController < ApplicationController
  def index
    #@visions = Vision.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/greetings/index.html.erb
<%= render 'pages/navbar'%>

app/views/histories/index.html.erb
<%= render 'pages/navbar'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarkgrafVonMeissen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/index.html.erb
<%= render 'pages/navbar'%>

app/views/members/show.html.erb
<%= render 'pages/navbar'%>

app/views/news/index.html.erb
<%= render 'pages/navbar'%>

app/views/news/show.html.erb
<%= render 'pages/navbar'%>

app/views/pages/_navbar.html.erb
<div class="container-logo">
  <img class="logo" src="https://res.cloudinary.com/titavon/image/upload/v1616018538/Logo_gcgcpl.png">
</div>
<!--Navbar-->
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #003157">
    <!--<a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>-->
    <div class="collapse navbar-collapse d-flex justify-content-center" id="navbarNav">
      <ul class="navbar-nav d-flex justify-content-center">
        <li class="nav-item active">
          <a class="nav-link" href="#"><%= link_to "Home", root_path%> <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link"><%= link_to "Greeting", greetings_path%></a>
        </li>
        <li class="nav-item">
          <a class="nav-link"><%= link_to "News", news_index_path%></a>
        </li>
        <li class="nav-item">
          <a class="nav-link"><%= link_to "History", histories_path%></a>
        </li>
        <li class="nav-item">
          <a class="nav-link"><%= link_to "Vision", visions_path%></a>
        </li>
        <li class="nav-item contact">
          <a class="nav-link"><%= link_to "Members", members_path%></a>
        </li>
      </ul>
    </div>
  </nav>
<!--end-->

app/views/pages/_slide.show.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://res.cloudinary.com/titavon/image/upload/v1616028678/dresdner-altstadt_umb8qp.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://res.cloudinary.com/titavon/image/upload/v1616028678/dresdner-altstadt_umb8qp.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://res.cloudinary.com/titavon/image/upload/v1616028678/dresdner-altstadt_umb8qp.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/pages/home.html.erb
<head>
<%= render 'navbar'%>
</head>

<body class="page-body">
  <div class="container" id="MainBackground">
    <%= render 'slide.show' %>
    <div class="Newest-events">
      <!--<img class="line-left" src="https://res.cloudinary.com/titavon/image/upload/v1616041002/Vector_skcfto.png">-->
      <h2>Newest Events</h2>
      <!--<img class="line-right" src="https://res.cloudinary.com/titavon/image/upload/v1616041002/Vector_skcfto.png">-->
      <div class="comtainer-events d-flex justify-content-center">
        <img src="https://res.cloudinary.com/titavon/image/upload/v1616028678/dresdner-altstadt_umb8qp.jpg" class="rounded float-left" alt="...">
        <img src="https://res.cloudinary.com/titavon/image/upload/v1616028678/dresdner-altstadt_umb8qp.jpg" class="rounded float-center" alt="...">
        <img src="https://res.cloudinary.com/titavon/image/upload/v1616028678/dresdner-altstadt_umb8qp.jpg" class="rounded float-right" alt="...">
      </div>
    </div>
    <div class="Highlights">
      <h2>Highlights<h2>
      <div class="highlight-container">
        <img src="https://res.cloudinary.com/titavon/image/upload/v1616028678/dresdner-altstadt_umb8qp.jpg" class="Round-Picture" alt="...">
      </div>
    </div>
  </div>
</body>

app/views/visions/index.html.erb
<%= render 'navbar'%>